# Generated by Django 3.0.7 on 2020-10-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201021_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setname', models.CharField(choices=[('생일선물', '생일선물'), ('추석선물세트', '추석선물세트'), ('이사집선물세트', '이사집선물세트')], max_length=200, null=True)),
                ('hastag', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('setform1', models.CharField(max_length=200, null=True)),
                ('setform2', models.CharField(max_length=200, null=True)),
                ('setform3', models.CharField(max_length=200, null=True)),
                ('setform4', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
