# Generated by Django 3.0.7 on 2020-10-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_presentset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(choices=[('퍼품샴푸컨디셔너', '퍼품샴푸컨디셔너'), ('머스크메론', '머스크메론'), ('과일큐브치즈', '과일큐브치즈'), ('SK2토너', 'SK2토너'), ('기모맨투맨5종택1', '기모맨투맨5종택1'), ('롯데제과종합선물세트', '롯데제과종합선물세트')], max_length=200, null=True)),
                ('hastag', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
