# Generated by Django 3.0.7 on 2020-10-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_photo_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentset',
            old_name='setform1',
            new_name='basket',
        ),
        migrations.RenameField(
            model_name='presentset',
            old_name='setform2',
            new_name='buy',
        ),
        migrations.RenameField(
            model_name='presentset',
            old_name='setform3',
            new_name='jjim',
        ),
        migrations.RenameField(
            model_name='presentset',
            old_name='setform4',
            new_name='like',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='like',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='point',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='presentset',
            name='setname',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productname',
        ),
        migrations.AddField(
            model_name='presentset',
            name='buyday',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='presentset',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='presentset',
            name='form',
            field=models.CharField(choices=[('구성1', '구성1'), ('구성2', '구성2'), ('구성3', '구성3'), ('구성4', '구성4')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='presentset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='presentset',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='presentset',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Product'),
        ),
        migrations.AddField(
            model_name='presentset',
            name='sell',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='jjim',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
