# Generated by Django 3.0.7 on 2020-10-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_presentset_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('hastag', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('save', models.IntegerField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(max_length=200, null=True)),
                ('hastag', models.CharField(max_length=200, null=True)),
                ('like', models.IntegerField(max_length=200, null=True)),
                ('sales', models.IntegerField(max_length=200, null=True)),
                ('cart', models.IntegerField(max_length=200, null=True)),
                ('save', models.IntegerField(max_length=200, null=True)),
                ('order', models.CharField(max_length=200, null=True)),
                ('packing', models.IntegerField(max_length=200, null=True)),
                ('packing_test', models.TextField(null=True)),
                ('item1', models.CharField(max_length=200, null=True)),
                ('item2', models.CharField(max_length=200, null=True)),
                ('item3', models.CharField(max_length=200, null=True)),
                ('item4', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='grade',
            field=models.CharField(choices=[('MVG', 'MVG'), ('VIP', 'VIP'), ('GOLD', 'GOLD'), ('ACE', 'ACE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rank',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Presentset',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='set',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Customer'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Customer'),
        ),
    ]
