# Generated by Django 3.0.7 on 2020-10-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201021_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='save',
        ),
    ]
