# Generated by Django 3.0.7 on 2020-10-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_item_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='set',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='set',
            name='item4',
        ),
        migrations.RemoveField(
            model_name='set',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='set',
            name='save',
        ),
    ]
