# Generated by Django 2.2.1 on 2020-10-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customer_zzim_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='set',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='set',
            name='hastag',
        ),
        migrations.RemoveField(
            model_name='set',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='set',
            name='order',
        ),
        migrations.RemoveField(
            model_name='set',
            name='packing_test',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/img/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
