# Generated by Django 2.2.1 on 2020-10-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201024_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='item',
            name='hastag',
        ),
        migrations.RemoveField(
            model_name='set',
            name='customer',
        ),
    ]
