# Generated by Django 2.2.1 on 2020-10-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201024_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='like',
        ),
        migrations.RemoveField(
            model_name='set',
            name='sales',
        ),
        migrations.AddField(
            model_name='customer',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app/static/img/'),
        ),
    ]
