# Generated by Django 2.2.1 on 2020-10-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201024_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set',
        ),
    ]
